(dp1
S'output'
p2
S"<type 'exceptions.IOError'> [Errno 2] No such file or directory: '/home/eddgt/Documentos/output_cron/suscrip_157/comprimido.zip'"
p3
sS'layer'
p4
S'/home/eddgt/public_html/web2py/web2py/applications/blog/controllers/configmenu.py'
p5
sS'code'
p6
S'# coding: utf8\n# intente algo como\ndef index(): return dict(message="hello from configmenu.py")\n\ndef articulos():\n    formulario =SQLFORM.smartgrid(db.articulo)\n    return locals()\n\ndef usuarios():\n    formulario =SQLFORM.grid(db.auth_user)\n    return locals()\n\ndef enviaCorreo():\n#mail.send(\'oulloa@televida.biz\',\n# \'Asunto del mensaje\',\n#  \'<html><img src="cid:foto" /></html>\',\n#  attachments = mail.Attachment(\'/home/eddgt/IMG_03072014_163916.png\', content_id=\'foto\'))\n\n        mail.send(to=[\'edmundo_ulloa@hotmail.com\'],\n          subject=\'test mail\',\n          # If reply_to is omitted, then mail.settings.sender is used\n          #reply_to=\'u...@example.com\',\n          message=\'hi there\',\n    #attachments = mail.Attachment(\'/home/eddgt/IMG_03072014_163916.png\', content_id=\'foto\')),\n    attachments = mail.Attachment(\'/home/eddgt/Documentos/output_cron/suscrip_157/comprimido.zip\',\n                                   content_id=\'base001\'))\n\nresponse._vars=response._caller(enviaCorreo)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/eddgt/public_html/web2py/web2py/gluon/restricted.py", line 220, in restricted\n    exec ccode in environment\n  File "/home/eddgt/public_html/web2py/web2py/applications/blog/controllers/configmenu.py", line 28, in <module>\n  File "/home/eddgt/public_html/web2py/web2py/gluon/globals.py", line 385, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/eddgt/public_html/web2py/web2py/applications/blog/controllers/configmenu.py", line 26, in enviaCorreo\n    content_id=\'base001\'))\n  File "/home/eddgt/public_html/web2py/web2py/gluon/tools.py", line 229, in __init__\n    payload = read_file(payload, \'rb\')\n  File "/home/eddgt/public_html/web2py/web2py/gluon/fileutils.py", line 100, in read_file\n    f = open(filename, mode)\nIOError: [Errno 2] No such file or directory: \'/home/eddgt/Documentos/output_cron/suscrip_157/comprimido.zip\'\n'
p11
s.